db:
  type: mongodb
  host: 192.168.10.99
  user: gradoDbUser
  password: XpWzZA8yXBe6uNPUCkJJ
  port: 27017
  database: cursuri-iso
  poolSize: 5
mq:
  host: 192.168.10.99
  port: 5672
  username: gradoMqUser
  password: JsvM2Aw8JaCfEbeDc3fZ
  retryCount: 10
  retryTimeout: 5